---
#Play
- hosts: role_server

  vars:
    repositories_names:
      - recettes_wiki
      - politique_wiki

  tasks:
    - name: "Install apache2"
      apt:
        name: apache2
        state: present

    - name: "Install php7"
      apt:
        name: php7.3
        state: present

    - name: "Download dokuwiki"
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src/dokuwiki-2020-07-29.zip
    
    - name: "Create repo dokuwiki in /usr/src"
      file:
        path: /usr/src/dokuwiki
        state: directory

    - name: "Extract dokuwiki2021.zip into /usr/src/dokuwiki"
      unarchive:
        src: /usr/src/dokuwiki-2020-07-29.zip
        dest: /usr/src/dokuwiki

    - name: "Create repo recettes_wiki et politique_wiki in /var/www/"
      file:
        path: "/var/www/{{ item }}"
        state: directory
      with_items: "{{ repositories_names }}" 

    - name: "Copy dokuwiki directory contents in recettes_wiki and politique_wiki"
      command: cp -r /usr/src/dokuwiki/.  "/var/www/{{ item }}/"
      with_items: "{{ repositories_names }}"
