---
#Play
- hosts: role_server

  tasks:

# Etape A2

    - name: "Install apache2 and php7"
      apt:
        name: 
          - apache2
          - php7.3
        state: present

# Etape A3

    - name: "Download dokuwiki"
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src/dokuwiki-2020-07-29.tgz

# Etape A4 
    
    - name: "Create repo dokuwiki in /usr/src"
      file:
        path: /usr/src/dokuwiki
        state: directory

    - name: "Extract dokuwiki-2020-07-29.tgz into /usr/src/dokuwiki"
      unarchive:
        remote_src: yes
        src: /usr/src/dokuwiki-2020-07-29.tgz
        dest: /usr/src/dokuwiki

    - name: "Delete dokuwiki-2020-07-29.tgz archive"
      file:
        path: /usr/src/dokuwiki-2020-07-29.tgz
        state: absent

# Etape B1

    - name: "Create repo recettes_wiki et politique_wiki in /var/www/"
      file:
        path: "/var/www/{{ item }}"
        state: directory
      with_items: "{{ repositories_names }}" 

# Etape B2

    - name: "Copy dokuwiki directory contents in recettes_wiki and politique_wiki"
      command: cp -r /usr/src/dokuwiki/.  "/var/www/{{ item }}/"
      with_items: "{{ repositories_names }}"

# Etape B3
 
    - name: "Allow apache to write"
      shell: cd /var/www/ && chown -R www-data:www-data "{{ item }}/" && cd
      with_items: "{{ repositories_names }}"

# Etape B4

    - name: "use 000-default.conf template for recettes_wiki.conf and politique_wiki.conf "
      template:
        src: /etc/apache2/site-available/000-default.conf
        dest: "/etc/apache2/site-available/{{ item }}.conf"
      with_items: "{{ repositories_names }}"

# Etape B5

    - name: "Enable virtualhost in apach2"
      command: a2ensite "{{ item }}"
      with_items: "{{ repositories_names }}"

    - name: "Reload apache2"
      command: systemctl reload apache2

# Etape B6
 
    - name: "Add DNS in /etc/hosts"
      shell: echo "127.0.0.1 {{ item }}" >> /etc/hosts
      with_items: "{{ repositories_names }}"
