---
#Play
- hosts: role_server

  tasks:
    - name: "Install apache2"
      apt:
        name: apache2
        state: present

    - name: "Install php7"
      apt:
        name: php7.3
        state: present

    - name: "Download dokuwiki"
      get_url:
        url: https://download.dokuwiki.org/src/dokuwiki/dokuwiki-stable.tgz
        dest: /usr/src/dokuwiki-2020-07-29.zip
    
    - name: "Create repo dokuwiki in /usr/src"
      file:
        path: /usr/src/dokuwiki
        state: directory

    - name: "Extract dokuwiki2021.zip into /usr/src/dokuwiki"
      unarchive:
        src: /usr/src/dokuwiki-2020-07-29.zip
        dest: /usr/src/dokuwiki

    - name: "Create repo dokuwiki-host in /var/www/dokuwiki-host"
      file:
        path: /var/www/dokuwiki-host
        state: directory
 
    - name: "Copy dokuwiki directory contents in"
      command: cp -r /usr/src/dokuwiki/. /var/www/dokuwiki-host/
