---
# vim: set ts=2 sw=2 smarttab et:

- hosts: role_db
  pre_tasks:
    - name: install python dependencies
      apt:
        name: python3-pymysql
        state: present

  roles:
    - role: adfinis-sygroup.mariadb
    
- hosts: role_app
    
  roles:
    - role: aalaesar.install_nextcloud     
